### ISSUE TITLE
Links to talent tree broken

### ISSUE THREAD

**Issue by jo-jstrm** [agentmerlin/vanilla-shaman-guide#1]
Thanks for the great guide! Unfortunately, the links to the talent trees are broken. Is the 0/5/46 [this one](https://www.wowhead.com/classic/guide/classes/shaman/healer-talent-builds-pve)?

**Comment by agentmerlin** [comment]
Fixed the links to use wowhead. One of the talent trees I was recommending was not listed in the wowhead guide
